const exams = [
  {
    label: "Hematologia",
    value: [
      { id: 1, value: "Hemoglobina (Hb)" },
      { id: 2, value: "Hemograma completo" },
      { id: 3, value: "Leucograma" },
      { id: 4, value: "Grupo Sanguineo e FR" },
      { id: 5, value: "Velocidade de Sedimentacao (VS)" },
      { id: 6, value: "Tempo de Coagulacao" },
      { id: 7, value: "Tempo de Hemorragia" },
      { id: 8, value: "Tempo de Protrombina / INR (TP)" },
      { id: 9, value: "Hemoglobina (Hb" },
      { id: 10, value: "Hemograma completo" },
      { id: 11, value: "Leucograma" },
      { id: 12, value: "Grupo Sanguíneo e FR" },
      { id: 13, value: "Velocidade de Sedimentação (VS)" },
      { id: 14, value: "Tempo de coagulação" },
      { id: 15, value: "Tempo de Hemorragia" },
      { id: 16, value: "Tempo de Protrombina / INR (TP)" },
      { id: 17, value: "Tempo de Tromboplastina (ATTP)" },
      { id: 18, value: "Teste de Falciformacao" },
    ],
  },
  {
    label: "Sorologia_Infectologia",
    value: [
      { id: 1, value: "Teste de Malaria" },
      { id: 2, value: "Pesquisa de plasmodium" },
      { id: 3, value: "R. Vidal" },
      { id: 4, value: "Teste de Tifoide" },
      { id: 5, value: "Teste de Dengue" },
      { id: 6, value: "Hepatite B (HBsAg)" },
      { id: 7, value: "Hepatite C (HCV)" },
      { id: 8, value: "Sifilis (VDRL)" },
      { id: 9, value: "HIV" },
      { id: 10, value: "Teste de Tuberculose Ac/Ag" },
      { id: 11, value: "Teste de Gravidez Sangue/Urina" },
      { id: 12, value: "Teste de Gonorreia" },
      { id: 13, value: "Helicobacter Pylori (H. Pylori)" },
      { id: 14, value: "Proteina C-reativa (PCR)" },
      { id: 15, value: "ASLO (TASO)" },
      { id: 16, value: "Fator Reumatoide (FR)" },
      { id: 17, value: "Hepatite A (HAV)" },
    ],
  },
  {
    label: "Urinologia",
    value: [
      { id: 1, value: "Urina II" },
      { id: 2, value: "EAS (Urina I)" },
      { id: 3, value: "Clearence da Creatinina" },
      { id: 4, value: "Proteina Total" },
    ],
  },
  {
    label: "Microbiologia",
    value: [
      { id: 1, value: "Exsudado Vaginal" },
      { id: 2, value: "Exsudado Uretral" },
      { id: 3, value: "Espermograma" },
      { id: 4, value: "Fezes / P. Sangue Oculto" },
      { id: 5, value: "BK directo (Expecto. 1 A, 2 A, 3 A)" },
    ],
  },
  {
    label: "Bioquimica",
    value: [
      { id: 1, value: "Glicemia jejum" },
      { id: 2, value: "Glicemia Pos-prandial" },
      { id: 3, value: "PTGO /1 H" },
      { id: 4, value: "PTGO / 2 H" },
      { id: 5, value: "Creatinina" },
      { id: 6, value: "Ureia" },
      { id: 7, value: "Acido Urico" },
      { id: 8, value: "T.G.P (ALT)" },
      { id: 9, value: "T.G.O (AST)" },
      { id: 10, value: "Fosfatasse Alcalina (ALP)" },
      { id: 11, value: "Bilirrubina Total" },
      { id: 12, value: "Bilirrubina Direta" },
      { id: 13, value: "Amilasa" },
      { id: 14, value: "CK-Nac" },
      { id: 15, value: "GGT" },
      { id: 16, value: "LDH" },
      { id: 17, value: "Albumina" },
      { id: 18, value: "Colesterol Total" },
      { id: 19, value: "Colesterol HDL - D / C" },
      { id: 20, value: "Colesterol LDL - D / C" },
      { id: 21, value: "FER" },
      { id: 22, value: "Triglicerido" },
      { id: 23, value: "Hemoglobina Glicada HB1AC" },
      { id: 24, value: "Alcool & Drogas" },
    ],
  },
  {
    label: "Imunologia_Hormonas",
    value: [
      { id: 1, value: "TSH" },
      { id: 2, value: "T3" },
      { id: 3, value: "T4" },
      { id: 4, value: "FT4" },
      { id: 5, value: "FSH" },
      { id: 6, value: "FT3" },
      { id: 7, value: "Progesterona" },
      { id: 8, value: "Testoterona" },
      { id: 9, value: "Prolactina" },
      { id: 10, value: "Ag. S. Prostata(PSA)" },
      { id: 11, value: "CA 125 II" },
      { id: 12, value: "Ferritina" },
      { id: 13, value: "TOXO lgG / lgM" },
      { id: 14, value: "TOXO lgM" },
      { id: 15, value: "CMG lgM / lgM" },
      { id: 16, value: "Quantiferon TB" },
    ],
  },
  {
    label: "Ionograma",
    value: [
      { id: 1, value: "Cl" },
      { id: 2, value: "Na" },
      { id: 3, value: "K" },
      { id: 4, value: "iCa" },
      { id: 5, value: "TCO2" },
      { id: 6, value: "pH" },
      { id: 7, value: "AnGap" },
    ],
  },
  {
    label: "Outros",
    value: [
      { id: 1, value: "Eletrocardiograma" },
      { id: 2, value: "Espirometria" },
      { id: 3, value: "MAPA" },
      { id: 4, value: "Citologia (Papanicolau)" },
      { id: 5, value: "PCR HPV" },
      { id: 6, value: "Hepatite B Carga Viral (PCR HBV)" },
      { id: 7, value: "Hepatite C Carga Viral (PCR HCV)" },
    ],
  },
];

export default exams;
