export const sintoms = [
  { id: 1, name: "Febre < 38ºC", code: "green" },
  { id: 2, name: "Febre > 38ºC", code: "yellow" },
  { id: 3, name: "Febre alta", code: "orange" },
  { id: 4, name: "Dor recente", code: "green" },
  { id: 5, name: "Dor moderada", code: "yellow" },
  { id: 6, name: "Dor Intensa", code: "orange" },
  { id: 7, name: "Diarreia sem sinais de desidratação", code: "green" },
  { id: 8, name: "Diarreia com sinais de desidratação", code: "yellow" },
  { id: 9, name: "Fezes com sangue", code: "orange" },
  { id: 10, name: "Vomito", code: "green" },
  { id: 11, name: "Vomitos abundantes", code: "yellow" },
  { id: 12, name: "Vómitos com sangue", code: "orange" },
  { id: 13, name: "Palidez", code: "yellow" },
  { id: 14, name: "Cefaleia", code: "green" },
  { id: 15, name: "Fraqueza", code: "yellow" },
  { id: 16, name: "Choque", code: "red" },
  { id: 17, name: "Possível Gravidez", code: "yellow" },
  { id: 18, name: "Dificuldade Respiratória", code: "orange" },
  { id: 19, name: "Perda de consciência", code: "red" },
  { id: 20, name: "Dor Torácica", code: "orange" },
  { id: 21, name: "Comprometimento das vias respiratórias", code: "red" },
];
